import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from "next/font/google";
import { Inter } from 'next/font/google'
import SiteHeader from './(client-components)/(Header)/SiteHeader'
import Footer from '@/components/Footer'
import FooterNav from '@/components/FooterNav'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className} >
      <body className={inter.className}>
        <SiteHeader />
         {children}
         <FooterNav />
         <Footer />
          </body>
    </html>
  )
}
